name = "self-docs"
compatibility_date = "2024-07-20"

[build]
command = "npm run build"
build_output_directory = "build"

[env.production]
name = "self-docs"

# Custom domain configuration
[[env.production.routes]]
pattern = "docs.self.app"

# Build environment variables
[env.production.vars]
NODE_VERSION = "20"