# Theme
theme: jekyll-theme-hydejack

# Site settings
title: SELF Chain Documentation
description: Documentation for SELF Chain - A self-sovereign blockchain platform
baseurl: "/self-chain-public"
url: "https://self-technology.github.io"
lang: en

# Hydejack Settings
hydejack:
  no_navbar: false
  no_drawer: false
  no_breadcrumbs: false
  no_structured_data: false
  no_theme_color: false
  
  # Dark mode
  dark_mode:
    dynamic: true
    icon: true

# Sidebar and theme customization
tagline: A self-sovereign blockchain platform
logo: /assets/img/logo.png
accent_image: /assets/img/sidebar-bg.jpg
accent_color: '#000000'
theme_color: '#000000'

# Permalinks
permalink: pretty

# Pagination
paginate: 10
paginate_path: /page/:num/

# Collections
collections:
  featured_categories:
    permalink: /:name/
    output: true

# Process all markdown files in docs
defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "page"
      sitemap: true

# File inclusion/exclusion
include:
  - .well-known
  - LICENSE.md

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
  footnote_backlink: '&#x21a9;&#xfe0e;'

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Author information
author:
  name: SELF Technology
  email: contact@self.app

# Menu
menu:
  - title: Documentation
    url: /documentation/
  - title: Getting Started
    url: /docs/About%20SELF/1.%20Introduction/Welcome
  - title: Architecture
    url: /docs/Architecture/SELF_Chain_Architecture
  - title: Development
    url: /docs/SDK/README

# Exclude files from build
exclude:
  - README.md
  - README-DOCS.md
  - DEPLOY_INSTRUCTIONS.md
  - SECURITY.md
  - Gemfile
  - Gemfile.lock
  - serve-local.sh
  - setup-migration.sh
  - setup-public-repo.sh
  - target/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

# Include custom CSS
sass:
  style: compressed
