# Theme
theme: jekyll-theme-hydejack

# Site settings
title: SELF Chain Documentation
description: Documentation for SELF Chain - A self-sovereign blockchain platform
baseurl: "/self-chain-public"
url: "https://self-technology.github.io"
lang: en

# Hydejack Settings
hydejack:
  no_navbar: false
  no_drawer: false
  no_breadcrumbs: false
  no_structured_data: false
  no_theme_color: false
  
  # Dark mode
  dark_mode:
    dynamic: true
    icon: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
  footnote_backlink: '&#x21a9;&#xfe0e;'

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Author information
author:
  name: SELF Technology
  email: contact@self.app

# Menu
menu:
  - title: About
    url: /about/
  - title: Documentation
    url: /docs/About%20SELF/1.%20Introduction/Welcome
  - title: Architecture
    url: /docs/Architecture/SELF_Chain_Architecture
  - title: Development
    url: /docs/SDK/README

# Exclude files from build
exclude:
  - README.md
  - README-DOCS.md
  - DEPLOY_INSTRUCTIONS.md
  - SECURITY.md
  - Gemfile
  - Gemfile.lock
  - serve-local.sh
  - setup-migration.sh
  - setup-public-repo.sh
  - target/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

# Include custom CSS
sass:
  style: compressed
