theme: jekyll-theme-cayman
title: SELF Chain Documentation
description: Documentation for SELF Chain - A self-sovereign blockchain platform
baseurl: "/self-chain-public"
url: "https://self-technology.github.io"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections for organizing docs
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
  - scope:
      path: "docs"
    values:
      layout: "default"

# Exclude files from build
exclude:
  - README.md
  - README-DOCS.md
  - DEPLOY_INSTRUCTIONS.md
  - SECURITY.md
  - Gemfile
  - Gemfile.lock
  - serve-local.sh
  - setup-migration.sh
  - setup-public-repo.sh
  - target/
