# Theme - Just the Docs
remote_theme: just-the-docs/just-the-docs@v0.8.2

# Site settings
title: SELF Chain
description: Documentation for SELF Chain - A self-sovereign blockchain platform
baseurl: "/self-chain-public"
url: "https://self-technology.github.io"
lang: en

# Just the Docs settings
color_scheme: custom
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Enable copy button on code blocks
enable_copy_code_button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2024 SELF Technology. All rights reserved."

# Process all markdown files in docs
defaults:
  - scope:
      path: "docs"
    values:
      layout: "default"
      nav_exclude: false
      search_exclude: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
  footnote_backlink: '&#x21a9;&#xfe0e;'

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Author information
author:
  name: SELF Technology
  email: contact@self.app

# Menu
menu:
  - title: Home
    url: /
  - title: Getting Started
    url: /docs/About%20SELF/1.%20Introduction/Welcome
  - title: Architecture
    url: /docs/Architecture/SELF_Chain_Architecture
  - title: Development
    url: /docs/SDK/README

# Exclude files from build
exclude:
  - README.md
  - README-DOCS.md
  - DEPLOY_INSTRUCTIONS.md
  - SECURITY.md
  - Gemfile
  - Gemfile.lock
  - serve-local.sh
  - setup-migration.sh
  - setup-public-repo.sh
  - target/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

# Include custom CSS
sass:
  style: compressed
