# Theme - using remote_theme for GitHub Pages
remote_theme: hydecorp/hydejack@9.1.6

# Site settings
title: SELF Chain Documentation
description: Documentation for SELF Chain - A self-sovereign blockchain platform
baseurl: "/self-chain-public"
url: "https://self-technology.github.io"
lang: en

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
  footnote_backlink: '&#x21a9;&#xfe0e;'

# Plugins (GitHub Pages supported)
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Author information
author:
  name: SELF Technology
  email: contact@self.app

# Exclude files from build
exclude:
  - README.md
  - README-DOCS.md
  - DEPLOY_INSTRUCTIONS.md
  - SECURITY.md
  - Gemfile
  - Gemfile.lock
  - serve-local.sh
  - setup-migration.sh
  - setup-public-repo.sh
  - target/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

# Include custom CSS
sass:
  style: compressed
