# SELF Documentation
title: SELF Documentation
description: The Future Of Technology Belongs To You
baseurl: "/self-chain-public" 
url: "https://self-technology.github.io"

# Use minimal theme that GitHub Pages supports
theme: minima

# Basic settings
markdown: kramdown
highlighter: rouge

# Plugins (only GitHub Pages supported ones)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - README.md
