[package]
name = "self-chain-public"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
plotters = "0.3"
tokio = { version = "1.32", features = ["full"] }
rand = "0.8"
anyhow = "1.0"
thiserror = "1.0"

