/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'doc',
      id: 'index',
      label: '👋 Welcome'
    },
    {
      type: 'doc',
      id: 'project-status/index',
      label: '📊 Project Status'
    },
    {
      type: 'category',
      label: 'ℹ️ About SELF',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'About SELF'
        }
      ]
    },
    {
      type: 'category',
      label: '📍 Roadmap',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Roadmap'
        }
      ]
    },
    {
      type: 'category',
      label: '🚀 Building on SELF',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Building-on-SELF'
        }
      ]
    },
    {
      type: 'category',
      label: '🛠️ Developing SELF',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Developing SELF'
        }
      ]
    },
    {
      type: 'category',
      label: '📚 Technical Docs',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Technical Docs'
        }
      ]
    }
  ],
};

module.exports = sidebars;