name = "self-docs"
compatibility_date = "2024-07-20"
pages_build_output_dir = "build"

[build]
command = "npm run build"

[env.production]
name = "self-docs"

# Custom domain configuration
[[env.production.routes]]
pattern = "docs.self.app"

# Build environment variables
[env.production.vars]
NODE_VERSION = "20"