[advisories]
ignore = [
    # ring 0.16.20 - comes from libp2p-tls dependency chain
    # We have a direct dependency on ring 0.17.5 to mitigate this
    "RUSTSEC-2025-0009",
    "RUSTSEC-2025-0010",
    
    # rsa 0.9.8 - comes from sqlx-mysql dependency
    # No fix available yet from sqlx
    "RUSTSEC-2023-0071",
]