visualization:
  output_dir: "./benchmark_results"
  width: 1200
  height: 800
  theme: Dark

benchmark:
  scenarios:
    - type: Surge
      baseline_tps: 1000
      peak_tps: 5000
      duration: 60
      surge_duration: 10
    - type: RampUp
      start_tps: 1000
      end_tps: 5000
      duration: 120
    - type: RealWorld
      transaction_profiles:
        - frequency: 1000
          size: 1024
          complexity: 5
          priority: 5
        - frequency: 500
          size: 2048
          complexity: 7
          priority: 7
      duration: 120
    - type: NetworkPartition
      partition_duration: 30
      partition_size: 0.3
      recovery_time: 30
    - type: HardwareFailure
      failure_rate: 0.1
      recovery_time: 60
