# SELF Chain Network Configuration Example
# Copy this file to network-config.toml and update for your network

[network]
# Network name
name = "self-mainnet"

# Network ID (1 for mainnet, other values for testnets)
network_id = 1

# Genesis block configuration
genesis_file = "./genesis.json"

[p2p]
# P2P protocol version
protocol_version = "1.0.0"

# Network magic number (for message validation)
magic = 0x53454C46  # "SELF" in hex

# Message size limits
max_message_size = 10485760  # 10MB
max_block_size = 5242880     # 5MB

# Peer management
peer_timeout = 30            # seconds
handshake_timeout = 10       # seconds
ping_interval = 60           # seconds

[tls]
# Enable TLS for peer connections
enabled = true

# TLS certificate settings
cert_file = "./certs/node.crt"
key_file = "./certs/node.key"
ca_file = "./certs/ca.crt"

# Auto-generate self-signed cert if files don't exist
auto_generate = true

[discovery]
# Peer discovery method: "mdns", "dht", or "both"
method = "both"

# mDNS discovery (local network)
mdns_enabled = true
mdns_interval = 30  # seconds

# DHT discovery (global network)
dht_enabled = true
dht_bootstrap_interval = 300  # seconds

[relay]
# Enable relay functionality for NAT traversal
enabled = true

# Maximum relay connections
max_relay_peers = 10

# Relay bandwidth limits (bytes/second)
relay_bandwidth_limit = 1048576  # 1MB/s

[nat]
# NAT traversal options
enable_upnp = true
enable_nat_pmp = true
enable_pcp = true

# External IP (leave empty for auto-detection)
external_ip = ""

[metrics]
# Enable network metrics collection
enabled = true

# Metrics export port (Prometheus format)
port = 9090

# Metrics collection interval
interval = 10  # seconds