# SELF Chain Testnet Configuration
# 
# ⚠️  WARNING: This is a TESTNET configuration template
# ⚠️  The testnet is not yet publicly deployed
# ⚠️  Expected deployment: Q3 2025
#
# This file documents the planned testnet configuration.
# Copy this file to testnet.toml when the testnet launches.

[network]
# Network identifier
chain_id = "self-testnet-001"
network_name = "SELF Chain Testnet"

# ⚠️  PLANNED: These nodes are not yet deployed
# When available, they will be public test nodes
bootstrap_nodes = [
    # Bootstrap nodes will be added when testnet launches
    # Expected format:
    # "https://testnet-1.self.app:8000",
    # "https://testnet-2.self.app:8000",
    # "https://testnet-3.self.app:8000"
]

# P2P network settings
p2p_port = 8000
api_port = 3030
external_address = ""  # Leave empty for automatic detection

[node]
# Node type: "validator", "full", "light"
# Note: Running a validator requires AI model setup
node_type = "full"
data_dir = "./testnet-data"

# Node identity (will be auto-generated if not provided)
node_id = ""
node_name = "my-testnet-node"

[consensus]
# Consensus algorithm
algorithm = "poai"  # Proof of AI
block_time_seconds = 10
min_validators = 3

# AI validation settings
ai_threshold = 0.7  # Minimum AI confidence score
ai_validation_enabled = true

[wallet]
# ⚠️  TESTNET WARNING: Use a NEW wallet for testnet - never use mainnet keys!
# Leave empty to generate a new testnet wallet
private_key = ""
keystore_path = "./testnet-keystore"

# Testnet faucet (planned for Q3 2025)
# The testnet currently operates without a token economy
faucet_url = "https://faucet.testnet.self.app"  # Not yet available
faucet_amount = "1000 TEST"  # Planned amount per request

[storage]
# Storage configuration
ipfs_enabled = true
ipfs_api = "http://127.0.0.1:5001"
ipfs_gateway = "http://127.0.0.1:8080"

# OrbitDB settings
orbitdb_enabled = true
orbitdb_directory = "./testnet-data/orbitdb"

# Storage limits for testnet
max_storage_gb = 10
max_bandwidth_gb = 50

[ai]
# AI model configuration for validators
# ⚠️  REQUIRED: Validators must run their own AI models
# Full nodes can operate without AI

# Local AI endpoint (OpenLLM recommended)
ai_endpoint = "http://localhost:11434/v1"
ai_model = "mistral:7b"  # Minimum model for testnet

# Future: Testnet AI service for light clients
use_testnet_ai = false  # Not yet available
testnet_ai_endpoint = "https://ai.testnet.self.app/v1"  # Planned
testnet_ai_api_key = ""  # Will be distributed via GitHub, Discord, and social channels

# AI resource limits
max_tokens = 1024
temperature = 0.7
timeout_seconds = 30

[security]
# ⚠️  TESTNET: Reduced security for easier testing
tls_enabled = false  # Will be enabled for public testnet
jwt_expiration_hours = 24

# API rate limiting
rate_limit_per_minute = 100
rate_limit_burst = 20

[monitoring]
# Testnet monitoring
metrics_enabled = true
metrics_port = 9100

# Planned services (Q3 2025)
explorer_url = "https://explorer.testnet.self.app"  # Not yet available
status_url = "https://status.testnet.self.app"     # Not yet available

# Health check
health_check_interval = 30
health_check_timeout = 10

[logging]
# Logging configuration
log_level = "info"  # Use "debug" for troubleshooting
log_format = "json"
log_file = "./testnet-logs/node.log"

# Log rotation
max_log_size_mb = 100
max_log_files = 5

[development]
# Development features (testnet only)
enable_debug_endpoints = false  # Set to true for debugging
enable_test_commands = false    # Set to true for testing
mock_ai_responses = false       # Set to true if no AI available

# Test transaction generator
auto_generate_transactions = false
transaction_interval_seconds = 60

# ============================================================================
# CURRENT STATUS (Q3 2025)
# ============================================================================
# 
# ✅ What's Working:
#    - Core blockchain implementation
#    - Local node deployment
#    - Basic PoAI consensus
#    - Transaction processing
#
# 🚧 In Active Development (Q3 2025):
#    - Public testnet deployment
#    - API Gateway
#    - Developer SDKs
#    - Token distribution system
#
# 📅 Coming Soon (Q4 2025):
#    - Public testnet launch
#    - Token faucet activation
#    - Block explorer
#    - Full API documentation
#
# ============================================================================

# QUICK START (When Testnet Launches)
# ============================================================================
# 
# 1. Copy this file:
#    cp testnet.example.toml testnet.toml
#
# 2. Install dependencies:
#    - Rust 1.70+
#    - IPFS daemon
#    - OpenLLM (for AI validation)
#
# 3. Build and run node:
#    cargo build --release
#    ./target/release/self-chain-node --config testnet.toml
#
# 4. Get testnet tokens (when available):
#    self-chain-cli faucet request --amount 1000
#
# 5. Check node status:
#    curl http://localhost:3030/status
#
# ============================================================================
# DEVELOPER RESOURCES
# ============================================================================
#
# Documentation: https://docs.self.app
# GitHub: https://github.com/SELF-Technology/self-chain-public
# Discord: https://discord.gg/WdMdVpA4C8
# Email: devs@self.app
#
# For the latest testnet status, see:
# https://docs.self.app/project-status
#
# ============================================================================