version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    reviewers:
      - "SELF-Technology/developers"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: "increase"
    target-branch: "main"
    ignore:
      - dependency-name: "axios"
        versions: ["<1.6.7"]
      - dependency-name: "ws"
        versions: ["<8.16.0"]
      - dependency-name: "next"
        versions: ["<15.3.3"]
